### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by geraldus** [Fuco1/yafmp#1]
Hi @Fuco1 !

I've came here from some old discussion on company-mode tracker.  I'm really interested in fuzzy matching for company and ido.  How can I test your program and integrate it with my Emacs?  Is it still maintained?  I'm on OS X El Capitan now with Emacs 25.0.91.1

**Comment by Fuco1** [comment]
Hi.

I guess piping stuff into it should work.  I've started with some server mode but haven't finished it.  I don't think this is ready for any serious integration yet.

**Comment by geraldus** [comment]
Ok, good to know.  I'm facing small `flx` lags when `M-x` opening list of commands, but then it works smooth.  However most interesting part for me would be fuzzy code completion.  I use `company-mode` and quite happy with it, but thoughts about fuzzy prefixes always haunt me :D 

I'll close this for now.
